name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fattosha
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#a90000&color_dots=#080808,#7f0508,#a90000,#d8c7b8
            dist/github-contribution-grid-snake-dark.svg?color_snake=#a90000&color_dots=#080808,#7f0508,#a90000,#d8c7b8

      - name: Push snake to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
