name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fattosha
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23a90000&color_dots=%23080808,%237f0508,%23a90000,%23d8c7b8,%23fbc6a8
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23a90000&color_dots=%23080808,%237f0508,%23a90000,%23d8c7b8,%23fbc6a8

      - name: Push snake to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
